### ISSUE TITLE
Sample tag content

### ISSUE THREAD

**Issue by stefanofalasca** [codeclou/advanced-codeblock-macro#3]
is not clear how put different content for different file download DDL. Your sample use one content (same) for two links DDL.

**Comment by clouless** [comment]
It is always one content. There cannot be multiple contents.
You can just use variables that get replaced in the content and produce different results.

When you use:
```
[testsystem 1]
base.url = www.myserver1.com
document.root = /www/server1

[testsystem 2]
base.url = www.myserver1.com
document.root = /www/server2

[content]
<VirtualHost *:80>
   DocumentRoot ${document.root}
   ServerName ${base.url}
   ...
</VirtualHost>
```

This will produce TWO Results:

testsystem1:

```
<VirtualHost *:80>
   DocumentRoot www.myserver1.com
   ServerName  /www/server1
   ...
</VirtualHost>
```

testsystem1:

```
<VirtualHost *:80>
   DocumentRoot www.myserver2.com
   ServerName  /www/server2
   ...
</VirtualHost>
```
